sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 32768 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell32/16/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell32/16/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 32768 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell32/16/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 32768 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell32/32/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell32/32/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 32768 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell32/32/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell64/16/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell64/16/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell64/16/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell64/32/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell64/32/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell64/32/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 131072 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell128/16/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell128/16/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 131072 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell128/16/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 131072 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell128/32/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell128/32/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 131072 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_mbw_mr -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_mbw/cxl_eth_2_cell128/32/output.log

