sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 2 -ppn 1 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/2/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/2/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 2 -ppn 1 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/2/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 4 -ppn 2 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/4/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/4/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 4 -ppn 2 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/4/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 8 -ppn 4 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/8/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/8/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 8 -ppn 4 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/8/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/16/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/16/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/16/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/32/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/32/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/eth_2/32/output.log

sleep 10
echo ' /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 2 -ppn 1 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/2/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/2/output.log
 /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 2 -ppn 1 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/2/output.log

sleep 10
echo ' /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 4 -ppn 2 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/4/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/4/output.log
 /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 4 -ppn 2 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/4/output.log

sleep 10
echo ' /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 8 -ppn 4 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/8/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/8/output.log
 /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 8 -ppn 4 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/8/output.log

sleep 10
echo ' /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/16/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/16/output.log
 /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/16/output.log

sleep 10
echo ' /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/32/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/32/output.log
 /home/sherry/miniconda3/envs/mpich/bin/mpirun -genv FI_PROVIDER tcp  -genv FI_TCP_IFACE ens1f1np1 -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile /home/sherry/osu-micro-benchmarks-7.4-mpich/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/ib_2/32/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 2 -ppn 1 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/2/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/2/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 2 -ppn 1 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/2/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 4 -ppn 2 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/4/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/4/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 4 -ppn 2 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/4/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 8 -ppn 4 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/8/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/8/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 8 -ppn 4 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/8/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/16/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/16/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 16 -ppn 8 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/16/output.log

sleep 10
echo 'FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/32/output.log' | tee /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/32/output.log
FI_PROVIDER=tcp  FI_TCP_IFACE=ens3f0 /home/sherry/miniconda3/envs/mpich_cxl/bin/mpirun -np 32 -ppn 16 -hostfile /home/sherry/mpi_sf/mpich_hostfile -genv MPIR_CVAR_CH4_SHM_POSIX_IQUEUE_CELL_SIZE 65536 /home/sherry/osu-micro-benchmarks-7.4-mpich_cxl/c/mpi/pt2pt/standard/osu_multi_lat -m :8388608 -i 2000 2>&1 | tee -a /home/sherry/MPI_over_CXL/mpi_run_bench/results/osu_pt2pt_multi_lat/cxl_eth_2_cell64/32/output.log

